import type { Metadata } from "next";
import "./globals.css";
import "tailwindcss";
import Appbar from "@repo/ui/components/appbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html> 
      <body>
        <Appbar/> 
        {children}
      </body>
    </html>
     

  );
}
